import type { ContentMode, VisualAsset } from '../lib/types';
export const promotionalPolicy = `PROMOTIONAL / SOFTWARE DISCOVERY: general tech/software audience. Source page first; default native contextual walkthrough, with contained real product screenshots, demos, audience-valuable evidence proving the product thesis, optional relevant secondary differentiation, one main practical limitation and a clear final takeaway. Build discovery: thesis → core promise → understandable user-visible proof → supporting capabilities → optional secondary distinction → caveat → takeaway. Thesis relevance × audience value × visual demonstrability selects beats, with complexity/runtime costs and redundancy reducing priority; media availability cannot rescue a weak fact. No mandatory surprise. Aim for roughly 40–55 seconds / 80–115 spoken words when earned; shorter is fine. Omit engineering validation, reference renderers, byte identity, test methodology, installer/platform lists, protocol explanations, dependencies and internal architecture unless necessary to explain the product value. Speak a technical fact's user consequence only when explicitly source-supported. Keep numeric capability proof scoped to its tests. Automation can be one concise benefit, without CLI/JSON/MCP syntax. Never speak series branding. Raw code, commands, terminal cards and generated code graphics are disabled. README/page is the spatial spine; optional product media supplies evidence. Detail is temporary, explicitly narrated, established wide first and followed by a return. Static views are acceptable. Every visual needs a complete narration beat, reason, section, optional justified focal area, dwell and entry/exit destination.`;
export function codeVisualsAllowed(mode:ContentMode='promotional') { return mode!=='promotional'; }
export function narrationPolicy(mode:ContentMode='promotional') {
 if(mode==='developer')return 'DEVELOPER: audience understands implementation details, protocols, architecture and engineering validation. Explain the selected mechanism and its explicitly documented tradeoffs; technical caveats, test scope, commands and code can earn runtime. Do not invent practical benefits from implementation evidence.';
 if(mode==='tutorial')return 'TUTORIAL: audience is following reproducible steps, commands and code. Explain the selected actions in order using exact sourced syntax and prerequisites. Include limitations that affect completing the task. Do not turn instructions into promotional claims.';
 return promotionalPolicy;
}
export function eligibleVisual(asset:VisualAsset,mode:ContentMode='promotional') { return asset.type!=='code' || codeVisualsAllowed(mode); }
export const promotionalCaptureCSS = 'pre, code, .highlight, .highlight-source-shell, .code-block, .language-json, .language-bash, [data-code-block], .terminal, [role="terminal"]{display:none!important}';
